/*
 * DevOps Secrets Vault API
 *
 * The purpose of this application is to provide a simple service for storing and getting secrets
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

// User contains user data along with user metadata
type UserResponse struct {
	// Created date
	Created string `json:"created,omitempty"`
	// Who created
	CreatedBy string `json:"createdBy,omitempty"`
	// The display name of the user
	DisplayName string `json:"displayName,omitempty"`
	// External identifier, such as an AWS arn for 3rd party authentication
	ExternalId string `json:"externalId,omitempty"`
	// the id for this item
	Id string `json:"id,omitempty"`
	// Last updated date
	LastModified string `json:"lastModified,omitempty"`
	// Who performed the last modification
	LastModifiedBy string `json:"lastModifiedBy,omitempty"`
	// Provider name defined in the authentication settings section of configuration
	Provider string `json:"provider,omitempty"`
	// The name of the user
	UserName string `json:"userName,omitempty"`
	// Current version
	Version string `json:"version,omitempty"`
}
