/*
 * DevOps Secrets Vault API
 *
 * The purpose of this application is to provide a simple service for storing and getting secrets
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Authentication is the 3rd party authentication providers
type Authentication struct {
	ID string `json:"ID,omitempty"`
	Name string `json:"name,omitempty"`
	Properties *AuthProperties `json:"properties,omitempty"`
	Type_ string `json:"type,omitempty"`
}
