/*
 * DevOps Secrets Vault API
 *
 * The purpose of this application is to provide a simple service for storing and getting secrets
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClientCreate struct {
	// Client description
	Description string `json:"description,omitempty"`
	// Name of role to assign to client
	Role string `json:"role"`
	// TTL expiration in seconds
	Ttl int64 `json:"ttl,omitempty"`
	Url bool `json:"url,omitempty"`
	UrlTTL int64 `json:"urlTTL,omitempty"`
	// Uses the number of times the client credential can be read. if set to 0, it can be used infinitely. default is 0.
	UsesLimit int64 `json:"usesLimit,omitempty"`
}
