/*
 * DevOps Secrets Vault API
 *
 * The purpose of this application is to provide a simple service for storing and getting secrets
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

// PasswordChange model for submitting password change requests
type PasswordChangeModel struct {
	// The user's current password
	CurrentPassword string `json:"currentPassword"`
	// The new password to use
	NewPassword string `json:"newPassword"`
}
