// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/audit"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/break_glass"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/clients"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/config"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/eaa_s_auto"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/eaa_s_manual"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/engines"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/groups"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/home"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/key"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/p_k_i"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/policies"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/pools"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/roles"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/s_i_e_m"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/secrets"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/settings"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/tasks"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/tokens"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/usage"
	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/client/users"
)

// Default dev ops secrets vault API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "secretsvaultcloud.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new dev ops secrets vault API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *DevOpsSecretsVaultAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new dev ops secrets vault API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *DevOpsSecretsVaultAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new dev ops secrets vault API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *DevOpsSecretsVaultAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(DevOpsSecretsVaultAPI)
	cli.Transport = transport
	cli.Audit = audit.New(transport, formats)
	cli.BreakGlass = break_glass.New(transport, formats)
	cli.Clients = clients.New(transport, formats)
	cli.Config = config.New(transport, formats)
	cli.EaasAuto = eaa_s_auto.New(transport, formats)
	cli.EaasManual = eaa_s_manual.New(transport, formats)
	cli.Engines = engines.New(transport, formats)
	cli.Groups = groups.New(transport, formats)
	cli.Home = home.New(transport, formats)
	cli.Key = key.New(transport, formats)
	cli.Pki = p_k_i.New(transport, formats)
	cli.Policies = policies.New(transport, formats)
	cli.Pools = pools.New(transport, formats)
	cli.Roles = roles.New(transport, formats)
	cli.Siem = s_i_e_m.New(transport, formats)
	cli.Secrets = secrets.New(transport, formats)
	cli.Settings = settings.New(transport, formats)
	cli.Tasks = tasks.New(transport, formats)
	cli.Tokens = tokens.New(transport, formats)
	cli.Usage = usage.New(transport, formats)
	cli.Users = users.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// DevOpsSecretsVaultAPI is a client for dev ops secrets vault API
type DevOpsSecretsVaultAPI struct {
	Audit audit.ClientService

	BreakGlass break_glass.ClientService

	Clients clients.ClientService

	Config config.ClientService

	EaasAuto eaa_s_auto.ClientService

	EaasManual eaa_s_manual.ClientService

	Engines engines.ClientService

	Groups groups.ClientService

	Home home.ClientService

	Key key.ClientService

	Pki p_k_i.ClientService

	Policies policies.ClientService

	Pools pools.ClientService

	Roles roles.ClientService

	Siem s_i_e_m.ClientService

	Secrets secrets.ClientService

	Settings settings.ClientService

	Tasks tasks.ClientService

	Tokens tokens.ClientService

	Usage usage.ClientService

	Users users.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *DevOpsSecretsVaultAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Audit.SetTransport(transport)
	c.BreakGlass.SetTransport(transport)
	c.Clients.SetTransport(transport)
	c.Config.SetTransport(transport)
	c.EaasAuto.SetTransport(transport)
	c.EaasManual.SetTransport(transport)
	c.Engines.SetTransport(transport)
	c.Groups.SetTransport(transport)
	c.Home.SetTransport(transport)
	c.Key.SetTransport(transport)
	c.Pki.SetTransport(transport)
	c.Policies.SetTransport(transport)
	c.Pools.SetTransport(transport)
	c.Roles.SetTransport(transport)
	c.Siem.SetTransport(transport)
	c.Secrets.SetTransport(transport)
	c.Settings.SetTransport(transport)
	c.Tasks.SetTransport(transport)
	c.Tokens.SetTransport(transport)
	c.Usage.SetTransport(transport)
	c.Users.SetTransport(transport)
}
