// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAuthSettingsByVersionParams creates a new GetAuthSettingsByVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthSettingsByVersionParams() *GetAuthSettingsByVersionParams {
	return &GetAuthSettingsByVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthSettingsByVersionParamsWithTimeout creates a new GetAuthSettingsByVersionParams object
// with the ability to set a timeout on a request.
func NewGetAuthSettingsByVersionParamsWithTimeout(timeout time.Duration) *GetAuthSettingsByVersionParams {
	return &GetAuthSettingsByVersionParams{
		timeout: timeout,
	}
}

// NewGetAuthSettingsByVersionParamsWithContext creates a new GetAuthSettingsByVersionParams object
// with the ability to set a context for a request.
func NewGetAuthSettingsByVersionParamsWithContext(ctx context.Context) *GetAuthSettingsByVersionParams {
	return &GetAuthSettingsByVersionParams{
		Context: ctx,
	}
}

// NewGetAuthSettingsByVersionParamsWithHTTPClient creates a new GetAuthSettingsByVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthSettingsByVersionParamsWithHTTPClient(client *http.Client) *GetAuthSettingsByVersionParams {
	return &GetAuthSettingsByVersionParams{
		HTTPClient: client,
	}
}

/* GetAuthSettingsByVersionParams contains all the parameters to send to the API endpoint
   for the get auth settings by version operation.

   Typically these are written to a http.Request.
*/
type GetAuthSettingsByVersionParams struct {

	/* Name.

	   Full name to lookup authentication settings by.
	*/
	Name string

	/* Version.

	   Versions to return.

	   Format: int64
	*/
	Version int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auth settings by version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthSettingsByVersionParams) WithDefaults() *GetAuthSettingsByVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth settings by version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthSettingsByVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) WithTimeout(timeout time.Duration) *GetAuthSettingsByVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) WithContext(ctx context.Context) *GetAuthSettingsByVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) WithHTTPClient(client *http.Client) *GetAuthSettingsByVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) WithName(name string) *GetAuthSettingsByVersionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) SetName(name string) {
	o.Name = name
}

// WithVersion adds the version to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) WithVersion(version int64) *GetAuthSettingsByVersionParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get auth settings by version params
func (o *GetAuthSettingsByVersionParams) SetVersion(version int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthSettingsByVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", swag.FormatInt64(o.Version)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
