// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSecretDescriptionParams creates a new GetSecretDescriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSecretDescriptionParams() *GetSecretDescriptionParams {
	return &GetSecretDescriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSecretDescriptionParamsWithTimeout creates a new GetSecretDescriptionParams object
// with the ability to set a timeout on a request.
func NewGetSecretDescriptionParamsWithTimeout(timeout time.Duration) *GetSecretDescriptionParams {
	return &GetSecretDescriptionParams{
		timeout: timeout,
	}
}

// NewGetSecretDescriptionParamsWithContext creates a new GetSecretDescriptionParams object
// with the ability to set a context for a request.
func NewGetSecretDescriptionParamsWithContext(ctx context.Context) *GetSecretDescriptionParams {
	return &GetSecretDescriptionParams{
		Context: ctx,
	}
}

// NewGetSecretDescriptionParamsWithHTTPClient creates a new GetSecretDescriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSecretDescriptionParamsWithHTTPClient(client *http.Client) *GetSecretDescriptionParams {
	return &GetSecretDescriptionParams{
		HTTPClient: client,
	}
}

/* GetSecretDescriptionParams contains all the parameters to send to the API endpoint
   for the get secret description operation.

   Typically these are written to a http.Request.
*/
type GetSecretDescriptionParams struct {

	/* ID.

	   Unique uuid identifying a secret
	*/
	ID *string

	/* Path.

	   The full secret path i.e. servers/prod/webserver-01
	*/
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get secret description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSecretDescriptionParams) WithDefaults() *GetSecretDescriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get secret description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSecretDescriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get secret description params
func (o *GetSecretDescriptionParams) WithTimeout(timeout time.Duration) *GetSecretDescriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get secret description params
func (o *GetSecretDescriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get secret description params
func (o *GetSecretDescriptionParams) WithContext(ctx context.Context) *GetSecretDescriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get secret description params
func (o *GetSecretDescriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get secret description params
func (o *GetSecretDescriptionParams) WithHTTPClient(client *http.Client) *GetSecretDescriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get secret description params
func (o *GetSecretDescriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get secret description params
func (o *GetSecretDescriptionParams) WithID(id *string) *GetSecretDescriptionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get secret description params
func (o *GetSecretDescriptionParams) SetID(id *string) {
	o.ID = id
}

// WithPath adds the path to the get secret description params
func (o *GetSecretDescriptionParams) WithPath(path string) *GetSecretDescriptionParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the get secret description params
func (o *GetSecretDescriptionParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *GetSecretDescriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
