// Code generated by go-swagger; DO NOT EDIT.

package eaa_s_auto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateKeyParams creates a new CreateKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateKeyParams() *CreateKeyParams {
	return &CreateKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateKeyParamsWithTimeout creates a new CreateKeyParams object
// with the ability to set a timeout on a request.
func NewCreateKeyParamsWithTimeout(timeout time.Duration) *CreateKeyParams {
	return &CreateKeyParams{
		timeout: timeout,
	}
}

// NewCreateKeyParamsWithContext creates a new CreateKeyParams object
// with the ability to set a context for a request.
func NewCreateKeyParamsWithContext(ctx context.Context) *CreateKeyParams {
	return &CreateKeyParams{
		Context: ctx,
	}
}

// NewCreateKeyParamsWithHTTPClient creates a new CreateKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateKeyParamsWithHTTPClient(client *http.Client) *CreateKeyParams {
	return &CreateKeyParams{
		HTTPClient: client,
	}
}

/* CreateKeyParams contains all the parameters to send to the API endpoint
   for the create key operation.

   Typically these are written to a http.Request.
*/
type CreateKeyParams struct {

	/* Path.

	   The full key path, for example, mykeys/key01
	*/
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateKeyParams) WithDefaults() *CreateKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create key params
func (o *CreateKeyParams) WithTimeout(timeout time.Duration) *CreateKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create key params
func (o *CreateKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create key params
func (o *CreateKeyParams) WithContext(ctx context.Context) *CreateKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create key params
func (o *CreateKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create key params
func (o *CreateKeyParams) WithHTTPClient(client *http.Client) *CreateKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create key params
func (o *CreateKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPath adds the path to the create key params
func (o *CreateKeyParams) WithPath(path string) *CreateKeyParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the create key params
func (o *CreateKeyParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *CreateKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
