// Code generated by go-swagger; DO NOT EDIT.

package eaa_s_auto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDecryptParams creates a new DecryptParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDecryptParams() *DecryptParams {
	return &DecryptParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDecryptParamsWithTimeout creates a new DecryptParams object
// with the ability to set a timeout on a request.
func NewDecryptParamsWithTimeout(timeout time.Duration) *DecryptParams {
	return &DecryptParams{
		timeout: timeout,
	}
}

// NewDecryptParamsWithContext creates a new DecryptParams object
// with the ability to set a context for a request.
func NewDecryptParamsWithContext(ctx context.Context) *DecryptParams {
	return &DecryptParams{
		Context: ctx,
	}
}

// NewDecryptParamsWithHTTPClient creates a new DecryptParams object
// with the ability to set a custom HTTPClient for a request.
func NewDecryptParamsWithHTTPClient(client *http.Client) *DecryptParams {
	return &DecryptParams{
		HTTPClient: client,
	}
}

/* DecryptParams contains all the parameters to send to the API endpoint
   for the decrypt operation.

   Typically these are written to a http.Request.
*/
type DecryptParams struct {

	/* Ciphertext.

	   A value to be decrypted
	*/
	Ciphertext []uint8

	/* Path.

	   The path to data key
	*/
	Path string

	/* Version.

	   The version of the key with which to decrypt data
	*/
	Version *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the decrypt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DecryptParams) WithDefaults() *DecryptParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the decrypt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DecryptParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the decrypt params
func (o *DecryptParams) WithTimeout(timeout time.Duration) *DecryptParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the decrypt params
func (o *DecryptParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the decrypt params
func (o *DecryptParams) WithContext(ctx context.Context) *DecryptParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the decrypt params
func (o *DecryptParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the decrypt params
func (o *DecryptParams) WithHTTPClient(client *http.Client) *DecryptParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the decrypt params
func (o *DecryptParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCiphertext adds the ciphertext to the decrypt params
func (o *DecryptParams) WithCiphertext(ciphertext []uint8) *DecryptParams {
	o.SetCiphertext(ciphertext)
	return o
}

// SetCiphertext adds the ciphertext to the decrypt params
func (o *DecryptParams) SetCiphertext(ciphertext []uint8) {
	o.Ciphertext = ciphertext
}

// WithPath adds the path to the decrypt params
func (o *DecryptParams) WithPath(path string) *DecryptParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the decrypt params
func (o *DecryptParams) SetPath(path string) {
	o.Path = path
}

// WithVersion adds the version to the decrypt params
func (o *DecryptParams) WithVersion(version *string) *DecryptParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the decrypt params
func (o *DecryptParams) SetVersion(version *string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *DecryptParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Ciphertext != nil {

		// binding items for ciphertext
		joinedCiphertext := o.bindParamCiphertext(reg)

		// query array param ciphertext
		if err := r.SetQueryParam("ciphertext", joinedCiphertext...); err != nil {
			return err
		}
	}

	// query param path
	qrPath := o.Path
	qPath := qrPath
	if qPath != "" {

		if err := r.SetQueryParam("path", qPath); err != nil {
			return err
		}
	}

	if o.Version != nil {

		// query param version
		var qrVersion string

		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := qrVersion
		if qVersion != "" {

			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamDecrypt binds the parameter ciphertext
func (o *DecryptParams) bindParamCiphertext(formats strfmt.Registry) []string {
	ciphertextIR := o.Ciphertext

	var ciphertextIC []string
	for _, ciphertextIIR := range ciphertextIR { // explode []uint8

		ciphertextIIV := swag.FormatUint8(ciphertextIIR) // uint8 as string
		ciphertextIC = append(ciphertextIC, ciphertextIIV)
	}

	// items.CollectionFormat: ""
	ciphertextIS := swag.JoinByFormat(ciphertextIC, "")

	return ciphertextIS
}
