// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSearchRolesParams creates a new SearchRolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchRolesParams() *SearchRolesParams {
	return &SearchRolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchRolesParamsWithTimeout creates a new SearchRolesParams object
// with the ability to set a timeout on a request.
func NewSearchRolesParamsWithTimeout(timeout time.Duration) *SearchRolesParams {
	return &SearchRolesParams{
		timeout: timeout,
	}
}

// NewSearchRolesParamsWithContext creates a new SearchRolesParams object
// with the ability to set a context for a request.
func NewSearchRolesParamsWithContext(ctx context.Context) *SearchRolesParams {
	return &SearchRolesParams{
		Context: ctx,
	}
}

// NewSearchRolesParamsWithHTTPClient creates a new SearchRolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchRolesParamsWithHTTPClient(client *http.Client) *SearchRolesParams {
	return &SearchRolesParams{
		HTTPClient: client,
	}
}

/* SearchRolesParams contains all the parameters to send to the API endpoint
   for the search roles operation.

   Typically these are written to a http.Request.
*/
type SearchRolesParams struct {

	/* Cursor.

	   C ursor to next batch of results
	*/
	Cursor *string

	/* Limit.

	   The maximum number of results per cursor

	   Format: int64
	*/
	Limit *int64

	/* SearchTerm.

	   Search pattern for names of roles to look up
	*/
	SearchTerm *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchRolesParams) WithDefaults() *SearchRolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchRolesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search roles params
func (o *SearchRolesParams) WithTimeout(timeout time.Duration) *SearchRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search roles params
func (o *SearchRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search roles params
func (o *SearchRolesParams) WithContext(ctx context.Context) *SearchRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search roles params
func (o *SearchRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search roles params
func (o *SearchRolesParams) WithHTTPClient(client *http.Client) *SearchRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search roles params
func (o *SearchRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the search roles params
func (o *SearchRolesParams) WithCursor(cursor *string) *SearchRolesParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the search roles params
func (o *SearchRolesParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithLimit adds the limit to the search roles params
func (o *SearchRolesParams) WithLimit(limit *int64) *SearchRolesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the search roles params
func (o *SearchRolesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSearchTerm adds the searchTerm to the search roles params
func (o *SearchRolesParams) WithSearchTerm(searchTerm *string) *SearchRolesParams {
	o.SetSearchTerm(searchTerm)
	return o
}

// SetSearchTerm adds the searchTerm to the search roles params
func (o *SearchRolesParams) SetSearchTerm(searchTerm *string) {
	o.SearchTerm = searchTerm
}

// WriteToRequest writes these params to a swagger request
func (o *SearchRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string

		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {

			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.SearchTerm != nil {

		// query param searchTerm
		var qrSearchTerm string

		if o.SearchTerm != nil {
			qrSearchTerm = *o.SearchTerm
		}
		qSearchTerm := qrSearchTerm
		if qSearchTerm != "" {

			if err := r.SetQueryParam("searchTerm", qSearchTerm); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
