// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateResponse Initialized engine and corresponding public / private key pair for signing engine tokens
//
// swagger:model CreateResponse
type CreateResponse struct {

	// Created date
	Created string `json:"created,omitempty"`

	// Who created the item
	CreatedBy string `json:"createdBy,omitempty"`

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`

	// the id for this item
	ID string `json:"id,omitempty"`

	// last heartbeat
	LastHeartbeat string `json:"lastHeartbeat,omitempty"`

	// Last updated date
	LastModified string `json:"lastModified,omitempty"`

	// Who performed the last modification
	LastModifiedBy string `json:"lastModifiedBy,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pool name
	PoolName string `json:"poolName,omitempty"`

	// private key
	PrivateKey string `json:"privateKey,omitempty"`

	// public key
	PublicKey string `json:"publicKey,omitempty"`

	// Current version
	Version string `json:"version,omitempty"`
}

// Validate validates this create response
func (m *CreateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create response based on context it is used
func (m *CreateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateResponse) UnmarshalBinary(b []byte) error {
	var res CreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
