// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ManualKeyData manual key data
//
// swagger:model ManualKeyData
type ManualKeyData struct {

	// metadata
	Metadata interface{} `json:"metadata,omitempty"`

	// Base64 encoded nonce to be used with key. If not provided, DSV generates it for the user.
	Nonce string `json:"nonce,omitempty"`

	// Base64 encoded private key
	// Required: true
	PrivateKey *string `json:"privateKey"`

	// Encryption scheme to be used.
	// Required: true
	Scheme *string `json:"scheme"`
}

// Validate validates this manual key data
func (m *ManualKeyData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrivateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScheme(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ManualKeyData) validatePrivateKey(formats strfmt.Registry) error {

	if err := validate.Required("privateKey", "body", m.PrivateKey); err != nil {
		return err
	}

	return nil
}

func (m *ManualKeyData) validateScheme(formats strfmt.Registry) error {

	if err := validate.Required("scheme", "body", m.Scheme); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this manual key data based on context it is used
func (m *ManualKeyData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ManualKeyData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ManualKeyData) UnmarshalBinary(b []byte) error {
	var res ManualKeyData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
