// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Role Role defines the role security principal and any mappings to 3rd party providers
//
// swagger:model Role
type Role struct {

	// Created date
	Created string `json:"created,omitempty"`

	// Who created
	CreatedBy string `json:"createdBy,omitempty"`

	// Role description
	Description string `json:"description,omitempty"`

	// External identifier, such as an AWS arn for 3rd party authentication
	ExternalID string `json:"externalId,omitempty"`

	// groups
	Groups []string `json:"groups"`

	// the id for this item
	ID string `json:"id,omitempty"`

	// Last updated date
	LastModified string `json:"lastModified,omitempty"`

	// Who performed the last modification
	LastModifiedBy string `json:"lastModifiedBy,omitempty"`

	// Name of role
	// Required: true
	Name *string `json:"name"`

	// Provider name defined in the authentication settings section of configuration
	Provider string `json:"provider,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this role
func (m *Role) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Role) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this role based on context it is used
func (m *Role) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Role) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Role) UnmarshalBinary(b []byte) error {
	var res Role
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
