// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/models"
)

// RestoreHomeSecretReader is a Reader for the RestoreHomeSecret structure.
type RestoreHomeSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestoreHomeSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestoreHomeSecretOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRestoreHomeSecretBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewRestoreHomeSecretUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRestoreHomeSecretForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRestoreHomeSecretNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRestoreHomeSecretInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRestoreHomeSecretOK creates a RestoreHomeSecretOK with default headers values
func NewRestoreHomeSecretOK() *RestoreHomeSecretOK {
	return &RestoreHomeSecretOK{}
}

/* RestoreHomeSecretOK describes a response with status code 200, with default header values.

no error
*/
type RestoreHomeSecretOK struct {
}

// IsSuccess returns true when this restore home secret o k response has a 2xx status code
func (o *RestoreHomeSecretOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this restore home secret o k response has a 3xx status code
func (o *RestoreHomeSecretOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore home secret o k response has a 4xx status code
func (o *RestoreHomeSecretOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this restore home secret o k response has a 5xx status code
func (o *RestoreHomeSecretOK) IsServerError() bool {
	return false
}

// IsCode returns true when this restore home secret o k response a status code equal to that given
func (o *RestoreHomeSecretOK) IsCode(code int) bool {
	return code == 200
}

func (o *RestoreHomeSecretOK) Error() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretOK ", 200)
}

func (o *RestoreHomeSecretOK) String() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretOK ", 200)
}

func (o *RestoreHomeSecretOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRestoreHomeSecretBadRequest creates a RestoreHomeSecretBadRequest with default headers values
func NewRestoreHomeSecretBadRequest() *RestoreHomeSecretBadRequest {
	return &RestoreHomeSecretBadRequest{}
}

/* RestoreHomeSecretBadRequest describes a response with status code 400, with default header values.

bad request
*/
type RestoreHomeSecretBadRequest struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this restore home secret bad request response has a 2xx status code
func (o *RestoreHomeSecretBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this restore home secret bad request response has a 3xx status code
func (o *RestoreHomeSecretBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore home secret bad request response has a 4xx status code
func (o *RestoreHomeSecretBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this restore home secret bad request response has a 5xx status code
func (o *RestoreHomeSecretBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this restore home secret bad request response a status code equal to that given
func (o *RestoreHomeSecretBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *RestoreHomeSecretBadRequest) Error() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretBadRequest  %+v", 400, o.Payload)
}

func (o *RestoreHomeSecretBadRequest) String() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretBadRequest  %+v", 400, o.Payload)
}

func (o *RestoreHomeSecretBadRequest) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *RestoreHomeSecretBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestoreHomeSecretUnauthorized creates a RestoreHomeSecretUnauthorized with default headers values
func NewRestoreHomeSecretUnauthorized() *RestoreHomeSecretUnauthorized {
	return &RestoreHomeSecretUnauthorized{}
}

/* RestoreHomeSecretUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type RestoreHomeSecretUnauthorized struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this restore home secret unauthorized response has a 2xx status code
func (o *RestoreHomeSecretUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this restore home secret unauthorized response has a 3xx status code
func (o *RestoreHomeSecretUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore home secret unauthorized response has a 4xx status code
func (o *RestoreHomeSecretUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this restore home secret unauthorized response has a 5xx status code
func (o *RestoreHomeSecretUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this restore home secret unauthorized response a status code equal to that given
func (o *RestoreHomeSecretUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *RestoreHomeSecretUnauthorized) Error() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretUnauthorized  %+v", 401, o.Payload)
}

func (o *RestoreHomeSecretUnauthorized) String() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretUnauthorized  %+v", 401, o.Payload)
}

func (o *RestoreHomeSecretUnauthorized) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *RestoreHomeSecretUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestoreHomeSecretForbidden creates a RestoreHomeSecretForbidden with default headers values
func NewRestoreHomeSecretForbidden() *RestoreHomeSecretForbidden {
	return &RestoreHomeSecretForbidden{}
}

/* RestoreHomeSecretForbidden describes a response with status code 403, with default header values.

forbidden
*/
type RestoreHomeSecretForbidden struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this restore home secret forbidden response has a 2xx status code
func (o *RestoreHomeSecretForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this restore home secret forbidden response has a 3xx status code
func (o *RestoreHomeSecretForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore home secret forbidden response has a 4xx status code
func (o *RestoreHomeSecretForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this restore home secret forbidden response has a 5xx status code
func (o *RestoreHomeSecretForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this restore home secret forbidden response a status code equal to that given
func (o *RestoreHomeSecretForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *RestoreHomeSecretForbidden) Error() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretForbidden  %+v", 403, o.Payload)
}

func (o *RestoreHomeSecretForbidden) String() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretForbidden  %+v", 403, o.Payload)
}

func (o *RestoreHomeSecretForbidden) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *RestoreHomeSecretForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestoreHomeSecretNotFound creates a RestoreHomeSecretNotFound with default headers values
func NewRestoreHomeSecretNotFound() *RestoreHomeSecretNotFound {
	return &RestoreHomeSecretNotFound{}
}

/* RestoreHomeSecretNotFound describes a response with status code 404, with default header values.

not found
*/
type RestoreHomeSecretNotFound struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this restore home secret not found response has a 2xx status code
func (o *RestoreHomeSecretNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this restore home secret not found response has a 3xx status code
func (o *RestoreHomeSecretNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore home secret not found response has a 4xx status code
func (o *RestoreHomeSecretNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this restore home secret not found response has a 5xx status code
func (o *RestoreHomeSecretNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this restore home secret not found response a status code equal to that given
func (o *RestoreHomeSecretNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *RestoreHomeSecretNotFound) Error() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretNotFound  %+v", 404, o.Payload)
}

func (o *RestoreHomeSecretNotFound) String() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretNotFound  %+v", 404, o.Payload)
}

func (o *RestoreHomeSecretNotFound) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *RestoreHomeSecretNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestoreHomeSecretInternalServerError creates a RestoreHomeSecretInternalServerError with default headers values
func NewRestoreHomeSecretInternalServerError() *RestoreHomeSecretInternalServerError {
	return &RestoreHomeSecretInternalServerError{}
}

/* RestoreHomeSecretInternalServerError describes a response with status code 500, with default header values.

server error
*/
type RestoreHomeSecretInternalServerError struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this restore home secret internal server error response has a 2xx status code
func (o *RestoreHomeSecretInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this restore home secret internal server error response has a 3xx status code
func (o *RestoreHomeSecretInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore home secret internal server error response has a 4xx status code
func (o *RestoreHomeSecretInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this restore home secret internal server error response has a 5xx status code
func (o *RestoreHomeSecretInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this restore home secret internal server error response a status code equal to that given
func (o *RestoreHomeSecretInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *RestoreHomeSecretInternalServerError) Error() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretInternalServerError  %+v", 500, o.Payload)
}

func (o *RestoreHomeSecretInternalServerError) String() string {
	return fmt.Sprintf("[GET /home/{principalName}/{path}/restore][%d] restoreHomeSecretInternalServerError  %+v", 500, o.Payload)
}

func (o *RestoreHomeSecretInternalServerError) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *RestoreHomeSecretInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
