// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRollbackHomeSecretParams creates a new RollbackHomeSecretParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRollbackHomeSecretParams() *RollbackHomeSecretParams {
	return &RollbackHomeSecretParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRollbackHomeSecretParamsWithTimeout creates a new RollbackHomeSecretParams object
// with the ability to set a timeout on a request.
func NewRollbackHomeSecretParamsWithTimeout(timeout time.Duration) *RollbackHomeSecretParams {
	return &RollbackHomeSecretParams{
		timeout: timeout,
	}
}

// NewRollbackHomeSecretParamsWithContext creates a new RollbackHomeSecretParams object
// with the ability to set a context for a request.
func NewRollbackHomeSecretParamsWithContext(ctx context.Context) *RollbackHomeSecretParams {
	return &RollbackHomeSecretParams{
		Context: ctx,
	}
}

// NewRollbackHomeSecretParamsWithHTTPClient creates a new RollbackHomeSecretParams object
// with the ability to set a custom HTTPClient for a request.
func NewRollbackHomeSecretParamsWithHTTPClient(client *http.Client) *RollbackHomeSecretParams {
	return &RollbackHomeSecretParams{
		HTTPClient: client,
	}
}

/* RollbackHomeSecretParams contains all the parameters to send to the API endpoint
   for the rollback home secret operation.

   Typically these are written to a http.Request.
*/
type RollbackHomeSecretParams struct {

	/* Path.

	   The full secret path i.e. servers/prod/webserver-01
	*/
	Path string

	/* PrincipalName.

	   Principal name
	*/
	PrincipalName string

	/* Version.

	   Versions to return

	   Format: int64
	*/
	Version int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rollback home secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RollbackHomeSecretParams) WithDefaults() *RollbackHomeSecretParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rollback home secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RollbackHomeSecretParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rollback home secret params
func (o *RollbackHomeSecretParams) WithTimeout(timeout time.Duration) *RollbackHomeSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rollback home secret params
func (o *RollbackHomeSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rollback home secret params
func (o *RollbackHomeSecretParams) WithContext(ctx context.Context) *RollbackHomeSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rollback home secret params
func (o *RollbackHomeSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rollback home secret params
func (o *RollbackHomeSecretParams) WithHTTPClient(client *http.Client) *RollbackHomeSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rollback home secret params
func (o *RollbackHomeSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPath adds the path to the rollback home secret params
func (o *RollbackHomeSecretParams) WithPath(path string) *RollbackHomeSecretParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the rollback home secret params
func (o *RollbackHomeSecretParams) SetPath(path string) {
	o.Path = path
}

// WithPrincipalName adds the principalName to the rollback home secret params
func (o *RollbackHomeSecretParams) WithPrincipalName(principalName string) *RollbackHomeSecretParams {
	o.SetPrincipalName(principalName)
	return o
}

// SetPrincipalName adds the principalName to the rollback home secret params
func (o *RollbackHomeSecretParams) SetPrincipalName(principalName string) {
	o.PrincipalName = principalName
}

// WithVersion adds the version to the rollback home secret params
func (o *RollbackHomeSecretParams) WithVersion(version int64) *RollbackHomeSecretParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the rollback home secret params
func (o *RollbackHomeSecretParams) SetVersion(version int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *RollbackHomeSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	// path param principalName
	if err := r.SetPathParam("principalName", o.PrincipalName); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", swag.FormatInt64(o.Version)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
