// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariiatuzovska/dsv-go-sdk/go-swagger/models"
)

// UpdateHomeSecretReader is a Reader for the UpdateHomeSecret structure.
type UpdateHomeSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateHomeSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateHomeSecretOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateHomeSecretBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateHomeSecretForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateHomeSecretNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateHomeSecretInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateHomeSecretOK creates a UpdateHomeSecretOK with default headers values
func NewUpdateHomeSecretOK() *UpdateHomeSecretOK {
	return &UpdateHomeSecretOK{}
}

/* UpdateHomeSecretOK describes a response with status code 200, with default header values.

no error
*/
type UpdateHomeSecretOK struct {
	Payload *models.ResponseModelFull
}

// IsSuccess returns true when this update home secret o k response has a 2xx status code
func (o *UpdateHomeSecretOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update home secret o k response has a 3xx status code
func (o *UpdateHomeSecretOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update home secret o k response has a 4xx status code
func (o *UpdateHomeSecretOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update home secret o k response has a 5xx status code
func (o *UpdateHomeSecretOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update home secret o k response a status code equal to that given
func (o *UpdateHomeSecretOK) IsCode(code int) bool {
	return code == 200
}

func (o *UpdateHomeSecretOK) Error() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretOK  %+v", 200, o.Payload)
}

func (o *UpdateHomeSecretOK) String() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretOK  %+v", 200, o.Payload)
}

func (o *UpdateHomeSecretOK) GetPayload() *models.ResponseModelFull {
	return o.Payload
}

func (o *UpdateHomeSecretOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseModelFull)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateHomeSecretBadRequest creates a UpdateHomeSecretBadRequest with default headers values
func NewUpdateHomeSecretBadRequest() *UpdateHomeSecretBadRequest {
	return &UpdateHomeSecretBadRequest{}
}

/* UpdateHomeSecretBadRequest describes a response with status code 400, with default header values.

bad request
*/
type UpdateHomeSecretBadRequest struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this update home secret bad request response has a 2xx status code
func (o *UpdateHomeSecretBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update home secret bad request response has a 3xx status code
func (o *UpdateHomeSecretBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update home secret bad request response has a 4xx status code
func (o *UpdateHomeSecretBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update home secret bad request response has a 5xx status code
func (o *UpdateHomeSecretBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update home secret bad request response a status code equal to that given
func (o *UpdateHomeSecretBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *UpdateHomeSecretBadRequest) Error() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateHomeSecretBadRequest) String() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateHomeSecretBadRequest) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *UpdateHomeSecretBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateHomeSecretForbidden creates a UpdateHomeSecretForbidden with default headers values
func NewUpdateHomeSecretForbidden() *UpdateHomeSecretForbidden {
	return &UpdateHomeSecretForbidden{}
}

/* UpdateHomeSecretForbidden describes a response with status code 403, with default header values.

forbidden
*/
type UpdateHomeSecretForbidden struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this update home secret forbidden response has a 2xx status code
func (o *UpdateHomeSecretForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update home secret forbidden response has a 3xx status code
func (o *UpdateHomeSecretForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update home secret forbidden response has a 4xx status code
func (o *UpdateHomeSecretForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update home secret forbidden response has a 5xx status code
func (o *UpdateHomeSecretForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update home secret forbidden response a status code equal to that given
func (o *UpdateHomeSecretForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *UpdateHomeSecretForbidden) Error() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretForbidden  %+v", 403, o.Payload)
}

func (o *UpdateHomeSecretForbidden) String() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretForbidden  %+v", 403, o.Payload)
}

func (o *UpdateHomeSecretForbidden) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *UpdateHomeSecretForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateHomeSecretNotFound creates a UpdateHomeSecretNotFound with default headers values
func NewUpdateHomeSecretNotFound() *UpdateHomeSecretNotFound {
	return &UpdateHomeSecretNotFound{}
}

/* UpdateHomeSecretNotFound describes a response with status code 404, with default header values.

not found
*/
type UpdateHomeSecretNotFound struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this update home secret not found response has a 2xx status code
func (o *UpdateHomeSecretNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update home secret not found response has a 3xx status code
func (o *UpdateHomeSecretNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update home secret not found response has a 4xx status code
func (o *UpdateHomeSecretNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update home secret not found response has a 5xx status code
func (o *UpdateHomeSecretNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update home secret not found response a status code equal to that given
func (o *UpdateHomeSecretNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *UpdateHomeSecretNotFound) Error() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretNotFound  %+v", 404, o.Payload)
}

func (o *UpdateHomeSecretNotFound) String() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretNotFound  %+v", 404, o.Payload)
}

func (o *UpdateHomeSecretNotFound) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *UpdateHomeSecretNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateHomeSecretInternalServerError creates a UpdateHomeSecretInternalServerError with default headers values
func NewUpdateHomeSecretInternalServerError() *UpdateHomeSecretInternalServerError {
	return &UpdateHomeSecretInternalServerError{}
}

/* UpdateHomeSecretInternalServerError describes a response with status code 500, with default header values.

server error
*/
type UpdateHomeSecretInternalServerError struct {
	Payload *models.HTTPError
}

// IsSuccess returns true when this update home secret internal server error response has a 2xx status code
func (o *UpdateHomeSecretInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update home secret internal server error response has a 3xx status code
func (o *UpdateHomeSecretInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update home secret internal server error response has a 4xx status code
func (o *UpdateHomeSecretInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update home secret internal server error response has a 5xx status code
func (o *UpdateHomeSecretInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update home secret internal server error response a status code equal to that given
func (o *UpdateHomeSecretInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *UpdateHomeSecretInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateHomeSecretInternalServerError) String() string {
	return fmt.Sprintf("[PUT /home/{principalName}/{path}][%d] updateHomeSecretInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateHomeSecretInternalServerError) GetPayload() *models.HTTPError {
	return o.Payload
}

func (o *UpdateHomeSecretInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
